#!/usr/bin/env python
"""Render ``milestone_1_report.md`` to ``milestone_1_report.pdf``.

Usage::

    python report/build_report.py

Handles the Markdown subset the report actually uses: ATX headings, blockquotes,
bullet and numbered lists, pipe tables, fenced code, ``**bold**``, ``*italic*``
and ``` `code` ```.  Figures listed in :data:`FIGURES` are appended as a plate
section if they have been generated by ``python main.py --demo all``.
"""

from __future__ import annotations

import os
import re
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (Image, KeepTogether, PageBreak, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
_WHICH = sys.argv[1] if len(sys.argv) > 1 else "1"
SRC_MD = os.path.join(HERE, f"milestone_{_WHICH}_report.md")
OUT_PDF = os.path.join(HERE, f"milestone_{_WHICH}_report.pdf")

#: (path relative to results/, caption) -- skipped silently if missing
FIGURES = [
    ("enhanced_images/contact_sheet.png",
     "Task 1 - enhancement: original, noise, Gaussian and median denoising, "
     "histogram equalisation, contrast stretching, unsharp masking and the "
     "Laplacian sharpener."),
    ("masks/threshold_contact_sheet.png",
     "Task 1d - thresholding: global, isodata, Otsu, adaptive mean, adaptive "
     "Gaussian, the colour distance to the estimated background, and the "
     "resulting foreground mask."),
    ("edge_visualisations/contact_sheet.png",
     "Task 2 - edge detection: Sobel and Prewitt magnitude and orientation, "
     "the Canny stages, and the effect of sigma and of the hysteresis levels."),
    ("contours/scene_labels_raw.png",
     "Task 3 - connected components of a dataset photograph before area "
     "filtering: 51 raw components, including clutter."),
    ("contours/scene_contours.png",
     "Task 3 - traced piece boundaries overlaid on the photograph."),
    ("contours/scene_pieces_normalised.png",
     "Task 3 - pieces cropped to their bounding boxes and rotated upright by "
     "their normalised orientation."),
    ("contours/described_pieces.png",
     "Task 4 - the four corners (red) and the four classified sides of each "
     "piece: green = tab, blue = blank, yellow = flat."),
    ("contours/colour_strips_piece0.png",
     "Task 4 - the colour signatures of one piece's four sides, three "
     "sampling depths each."),
    ("reconstructed_images/dataset_0718-10_Color_png.rf_reconstructed.png",
     "Section 9 - a dataset photograph reconstructed: the pieces are all "
     "isolated, described and placed, but the arrangement is wrong because "
     "the compatibility measure runs near chance on this mostly-white "
     "picture."),
    ("masks/dataset_0718-10_Color_png.rf_mask.png",
     "Section 9 - the foreground mask of the same photograph, after the "
     "distance-transform watershed has split the touching pieces."),
    ("reconstructed_images/demo_input.png",
     "Task 6 - synthetic validation input: a 4x5 puzzle, shuffled and "
     "rotated."),
    ("reconstructed_images/demo_4x5_reconstructed.png",
     "Task 6 - the reconstruction produced by the end-to-end routine "
     "(position, neighbour and rotation accuracy all 1.00)."),
    ("reconstructed_images/demo_original.png",
     "The original picture, for comparison."),
    ("reconstructed_images/puzzle_5x7_seed16_reconstructed.png",
     "A 35-piece puzzle with pieces at arbitrary rotations, reconstructed "
     "perfectly - the size of the dataset's jigsaw."),
]

#: Milestone 2 plates, written by ``main_milestone2.py --hard --figures``.
FIGURES_2 = [
    ("milestone2/figures/training_curves.png",
     "Task 3 - training behaviour: cross-entropy per epoch and the "
     "validation AUC both models were selected on.  The train and validation "
     "curves stay together, which is why both are diagnosed healthy."),
    ("milestone2/figures/test_split_comparison.png",
     "Task 5 - the unseen test split.  Every method reconstructs every "
     "puzzle, so this comparison is saturated and cannot rank them; only the "
     "ranking quality (AUC) separates the models here."),
    ("milestone2/figures/texture_sweep.png",
     "Task 5 - neighbour accuracy as the picture's texture is faded towards "
     "flat grey.  The hand-written measure collapses at texture 0.10; the "
     "Siamese network does not."),
    ("milestone2/figures/real_0718-10_Color_png.rf.f269500b6bdb1b871bf.png",
     "Task 5 - a dataset photograph, reconstructed by all three methods.  "
     "None of them solves it: the pieces tile into a neat rectangle and "
     "hardly any of them are in the right cell."),
    ("milestone2/figures/real_0718-14_Color_png.rf.7ba095874a51a7e4c95.png",
     "The photograph on which the Siamese network does best (neighbour 0.28 "
     "against the classical measure's 0.12) - still far from a solution."),
    ("milestone2/figures/real_0718-18_Color_png.rf.7ce49fe96d1498ecbab.png",
     "A third photograph.  Across all eight the learned models report much "
     "better seam quality while placing no more pieces correctly, which is "
     "what being confidently wrong outside the training distribution looks "
     "like."),
]


# --------------------------------------------------------------------------
# styles
# --------------------------------------------------------------------------
def make_styles():
    base = getSampleStyleSheet()
    s = {}
    s["title"] = ParagraphStyle("title", parent=base["Title"], fontSize=19,
                                leading=23, spaceAfter=6)
    s["h1"] = ParagraphStyle("h1", parent=base["Heading1"], fontSize=14,
                             leading=17, spaceBefore=16, spaceAfter=6,
                             textColor=colors.HexColor("#123a63"))
    s["h2"] = ParagraphStyle("h2", parent=base["Heading2"], fontSize=11.5,
                             leading=14, spaceBefore=11, spaceAfter=4,
                             textColor=colors.HexColor("#1d5286"))
    s["h3"] = ParagraphStyle("h3", parent=base["Heading3"], fontSize=10.5,
                             leading=13, spaceBefore=9, spaceAfter=3,
                             textColor=colors.HexColor("#2b6094"))
    s["body"] = ParagraphStyle("body", parent=base["BodyText"], fontSize=9.3,
                               leading=13, alignment=TA_JUSTIFY, spaceAfter=5)
    s["bullet"] = ParagraphStyle("bullet", parent=s["body"], leftIndent=14,
                                 bulletIndent=4, spaceAfter=2)
    s["quote"] = ParagraphStyle("quote", parent=s["body"], leftIndent=16,
                                rightIndent=10, spaceBefore=4, spaceAfter=6,
                                fontName="Helvetica-Oblique",
                                textColor=colors.HexColor("#333333"))
    s["code"] = ParagraphStyle("code", parent=base["Code"], fontSize=8,
                               leading=10, leftIndent=10,
                               backColor=colors.HexColor("#f2f4f7"),
                               spaceBefore=4, spaceAfter=6)
    s["cell"] = ParagraphStyle("cell", parent=s["body"], fontSize=8,
                               leading=10, alignment=0, spaceAfter=0)
    s["cellh"] = ParagraphStyle("cellh", parent=s["cell"],
                                fontName="Helvetica-Bold")
    s["caption"] = ParagraphStyle("caption", parent=s["body"], fontSize=8.2,
                                  leading=10.5,
                                  textColor=colors.HexColor("#444444"),
                                  spaceBefore=3, spaceAfter=12)
    return s


# --------------------------------------------------------------------------
# inline markdown -> reportlab markup
# --------------------------------------------------------------------------
#: The built-in Type 1 fonts are Latin-1 only, so every Greek or mathematical
#: character in the Markdown has to be spelled out or mapped before it reaches
#: reportlab -- otherwise it is silently dropped from the page.
TRANSLIT = {
    "α": "alpha", "β": "beta", "γ": "gamma", "δ": "delta",
    "ε": "epsilon", "θ": "theta", "λ": "lambda", "μ": "mu",
    "π": "pi", "ρ": "rho", "σ": "sigma", "τ": "tau",
    "φ": "phi", "χ": "chi", "ψ": "psi", "ω": "omega",
    "Δ": "Delta", "Σ": "sum", "Ω": "Omega",
    "∇": "grad", "√": "sqrt", "∞": "infinity",
    "≈": "~", "≠": "!=", "≤": "<=", "≥": ">=",
    "→": "->", "←": "<-", "⇒": "=>",
    "−": "-", "–": "-", "—": " - ",
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "…": "...", "·": ".", "•": "*",
    "‖": "||", "∥": "||", "⌈": "ceil(", "⌉": ")",
    "⌊": "floor(", "⌋": ")", "∩": " and ", "∪": " or ",
    "∖": " minus ", "∈": " in ",
    "₀": "0", "₁": "1", "₂": "2", "₃": "3",
    "⁴": "^4", "⁵": "^5", "⁶": "^6", "⁷": "^7",
    "ᵢ": "i", "ⱼ": "j",
    " ": " ",
}


def transliterate(text: str) -> str:
    """Replace characters the built-in PDF fonts cannot show."""
    out = []
    for ch in text:
        if ch in TRANSLIT:
            out.append(TRANSLIT[ch])
            continue
        try:
            ch.encode("latin-1")
            out.append(ch)
        except UnicodeEncodeError:
            out.append("?")
    return "".join(out)


def inline(text: str) -> str:
    text = transliterate(text)
    text = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    text = re.sub(r"`([^`]+)`", r'<font face="Courier" size="8.4">\1</font>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
    # markdown links -> "text (url)" is noisy in print; keep the text only
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", text)
    return text


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def is_separator(line: str) -> bool:
    return bool(re.fullmatch(r"\|?[\s:|-]+\|[\s:|-]*", line.strip())) and "-" in line


# --------------------------------------------------------------------------
# block parsing
# --------------------------------------------------------------------------
def build_story(md_text: str, styles, width: float):
    story = []
    lines = md_text.split("\n")
    i = 0
    para: list[str] = []

    def flush():
        if para:
            story.append(Paragraph(inline(" ".join(para)), styles["body"]))
            para.clear()

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            flush()
            i += 1
            continue

        if stripped.startswith("```"):
            flush()
            i += 1
            block = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1
            text = "<br/>".join(
                transliterate(l).replace("&", "&amp;").replace("<", "&lt;")
                 .replace(">", "&gt;").replace(" ", "&nbsp;") for l in block)
            story.append(Paragraph(text, styles["code"]))
            continue

        if stripped.startswith("---") and set(stripped) <= {"-"}:
            flush()
            story.append(Spacer(1, 6))
            i += 1
            continue

        m = re.match(r"^(#{1,4})\s+(.*)$", stripped)
        if m:
            flush()
            level = len(m.group(1))
            key = {1: "title", 2: "h1", 3: "h2", 4: "h3"}[level]
            story.append(Paragraph(inline(m.group(2)), styles[key]))
            i += 1
            continue

        if stripped.startswith(">"):
            flush()
            block = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                block.append(lines[i].strip().lstrip(">").strip())
                i += 1
            story.append(Paragraph(inline(" ".join(block)), styles["quote"]))
            continue

        # pipe table
        if stripped.startswith("|") and i + 1 < len(lines) and is_separator(lines[i + 1]):
            flush()
            header = split_row(stripped)
            i += 2
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(split_row(lines[i].strip()))
                i += 1
            data = [[Paragraph(inline(c), styles["cellh"]) for c in header]]
            for r in rows:
                r = (r + [""] * len(header))[:len(header)]
                data.append([Paragraph(inline(c), styles["cell"]) for c in r])
            n = len(header)
            first = max(width * 0.20, width / n)
            rest = (width - first) / max(n - 1, 1) if n > 1 else width
            col_widths = [first] + [rest] * (n - 1)
            t = Table(data, colWidths=col_widths, repeatRows=1, hAlign="LEFT")
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef5")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#b6c2d0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.white, colors.HexColor("#f7f9fb")]),
            ]))
            story.append(t)
            story.append(Spacer(1, 8))
            continue

        m = re.match(r"^\s*[-*]\s+(.*)$", line)
        if m:
            flush()
            story.append(Paragraph(inline(m.group(1)), styles["bullet"],
                                   bulletText="•"))
            i += 1
            continue

        m = re.match(r"^\s*(\d+)\.\s+(.*)$", line)
        if m:
            flush()
            story.append(Paragraph(inline(m.group(2)), styles["bullet"],
                                   bulletText=f"{m.group(1)}."))
            i += 1
            continue

        para.append(stripped)
        i += 1

    flush()
    return story


def figure_plates(styles, width: float):
    from PIL import Image as PILImage

    out = []
    figures = FIGURES_2 if _WHICH == "2" else FIGURES
    command = ("python main_milestone2.py --hard --figures" if _WHICH == "2"
               else "python main.py --run all")
    available = [(p, c) for p, c in figures
                 if os.path.exists(os.path.join(ROOT, "results", p))]
    if not available:
        return out
    out.append(PageBreak())
    out.append(Paragraph("Appendix - Figures", styles["h1"]))
    out.append(Paragraph(
        "Every figure below is produced by <font face=\"Courier\" size=\"8.4\">"
        f"{command}</font> and written to "
        "<font face=\"Courier\" size=\"8.4\">results/</font>.", styles["body"]))
    max_h = 12.5 * cm
    for rel, caption in available:
        path = os.path.join(ROOT, "results", rel)
        with PILImage.open(path) as im:
            iw, ih = im.size
        scale = min(width / iw, max_h / ih)
        out.append(KeepTogether([
            Image(path, width=iw * scale, height=ih * scale),
            Paragraph(f"<b>{rel}</b> &mdash; {caption}", styles["caption"]),
        ]))
    return out


def main():
    """Render the requested report.  ``python report/build_report.py 2``."""
    if not os.path.exists(SRC_MD):
        print(f"missing {SRC_MD}", file=sys.stderr)
        return 1
    with open(SRC_MD, encoding="utf-8") as fh:
        md_text = fh.read()

    styles = make_styles()
    doc = SimpleDocTemplate(
        OUT_PDF, pagesize=A4,
        leftMargin=2.0 * cm, rightMargin=2.0 * cm,
        topMargin=1.8 * cm, bottomMargin=1.8 * cm,
        title=f"CSE480 Milestone {_WHICH} - Jigsaw Puzzle Reconstruction",
        author="CSE480 Machine Vision")
    width = doc.width

    def footer(canvas, document):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#666666"))
        canvas.drawString(2.0 * cm, 1.1 * cm,
                          "CSE480 Machine Vision - Milestone " + _WHICH)
        canvas.drawRightString(A4[0] - 2.0 * cm, 1.1 * cm,
                               f"page {document.page}")
        canvas.restoreState()

    story = build_story(md_text, styles, width)
    story += figure_plates(styles, width)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    size_kb = os.path.getsize(OUT_PDF) / 1024
    print(f"wrote {os.path.relpath(OUT_PDF, ROOT)} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
